import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { GlobalProvider } from "./Providers/globalProvidor";
import SideBar from "./Components/SideBar";
import ContextProvidor from "./Providers/ContextProvidor";
import { ClerkProvider } from "@clerk/nextjs";
import AppInitializer from "./Initializer/AppInitializer";
import { Suspense } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <AppInitializer>
          <GlobalProvider>
            <body className=" flex h-full min-h-screen transition-all duration-300 ease-in-out">
              <Suspense
                fallback={<div className="w-64 bg-gray-100">Loading...</div>}
              >
                <SideBar />
              </Suspense>
              {children}
            </body>
          </GlobalProvider>
        </AppInitializer>
      </html>
    </ClerkProvider>
  );
}
