import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { GlobalProvider } from "./Providers/globalProvidor";
import SideBar from "./Components/SideBar";
import ContextProvidor from "./Providers/ContextProvidor";
import { ClerkProvider } from "@clerk/nextjs";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
      <GlobalProvider> 
      <body
        className=" flex h-full min-h-screen transition-all duration-300 ease-in-out"
      >
        <SideBar />
        {children}
      </body>
      </GlobalProvider>
    </html>
    </ClerkProvider>
  );
}
